# This Dockerfile is used for development purposes only.
# The main difference is the architecture - arm64 on mac, amd64 on fargate
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o time-api .

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /app/time-api .
EXPOSE 8000
CMD ["./time-api"]
